export default {
    SCHEDULER: {
        FETCH_SCHEDULERS: 'SCHEDULER_FETCH_SCHEDULERS',
        FETCH_SCHEDULERS_FULFILLED: 'SCHEDULER_FETCH_SCHEDULERS_FULFILLED',
        FAILURE: 'SCHEDULER_FAILURE',
        RESTORE_DEFAULTS: 'SCHEDULER_RESTORE_DEFAULTS'
    },
    JOB: {
        FETCH_JOBS: 'JOB_FETCH_JOBS',
        FETCH_JOBS_FULFILLED: 'JOB_FETCH_JOBS_FULFILLED',
        FAILURE: 'JOB_FAILURE',
        RESTORE_DEFAULTS: 'JOB_RESTORE_DEFAULTS',
    },
    TRIGGER: {
        FETCH_TRIGGERS: 'TRIGGER_FETCH_TRIGGERS',
        FETCH_TRIGGERS_FULFILLED: 'TRIGGER_FETCH_TRIGGERS_FULFILLED',
        FAILURE: 'TRIGGER_FAILURE',
        RESTORE_DEFAULTS: 'TRIGGER_RESTORE_DEFAULTS',
    }
};